# TIP: You can use hex codes with the following format: &#FFC0CB
message: "&cWhen setting a gamerule you should be using &n/mv gamerule&r&c. If you meant to use the vanilla gamerule command use &n/minecraft:gamerule&r&c"